dependsOn: []
name: pipeline
parameters:
  ">>channelLocation": KAFKA_BROKER_URL
spec:
  expectedParameters: {}
  location: null
  name: pypz.example.pipeline:DemoPipeline
  nestedInstanceType: <class 'pypz.core.specs.operator.Operator'>
  nestedInstances:
  - connections:
    - inputPortName: input_port
      source:
        instanceName: writer
        outputPortName: output_port
    dependsOn: []
    name: reader
    parameters:
      operatorImageName: accessible-repository/pypz-example
      replicationFactor: 3
    spec:
      expectedParameters:
        operatorImageName:
          currentValue: accessible-repository/pypz-example
          description: The image containing the operator's resources. It will be used
            mainly by the deployers.
          required: false
          type: str
        replicationFactor:
          currentValue: 3
          description: Determines, how many replicas shall be created from the original.
          required: false
          type: int
      location: null
      name: pypz.example.reader:DemoReaderOperator
      nestedInstanceType: <class 'pypz.core.specs.plugin.Plugin'>
      nestedInstances:
      - dependsOn: []
        name: input_port
        parameters:
          channelConfig: {}
          portOpenTimeoutMs: 0
          sequentialModeEnabled: false
          syncConnectionsOpen: false
        spec:
          expectedParameters:
            channelConfig:
              currentValue: {}
              description: Configuration of the channel as dictionary
              required: false
              type: dict
            channelLocation:
              currentValue: KAFKA_BROKER_URL
              description: Location of the channel resource
              required: true
              type: str
            portOpenTimeoutMs:
              currentValue: 0
              description: Specifies, how long the port shall wait for incomingconnections
              required: false
              type: int
            sequentialModeEnabled:
              currentValue: false
              description: If set to True, then this port will wait with the processing
                start until all the connected output ports are finished
              required: false
              type: bool
            syncConnectionsOpen:
              currentValue: false
              description: If set to True, the port will wait for every expectedoutput
                ports to be connected
              required: false
              type: bool
          location: null
          name: pypz.plugins.kafka_io.ports:KafkaChannelInputPort
          nestedInstanceType: null
          nestedInstances: null
          types:
          - <class 'pypz.core.specs.plugin.ResourceHandlerPlugin'>
          - <class 'pypz.core.specs.plugin.ExtendedPlugin'>
          - <class 'pypz.core.specs.plugin.InputPortPlugin'>
      - dependsOn: []
        name: logger
        parameters:
          logLevel: DEBUG
        spec:
          expectedParameters:
            logLevel:
              currentValue: DEBUG
              description: null
              required: false
              type: str
          location: null
          name: pypz.plugins.loggers.default:DefaultLoggerPlugin
          nestedInstanceType: null
          nestedInstances: null
          types:
          - <class 'pypz.core.specs.plugin.LoggerPlugin'>
      types:
      - <class 'pypz.core.specs.operator.Operator'>
  - connections: []
    dependsOn: []
    name: writer
    parameters:
      message: HelloWorld
      operatorImageName: accessible-repository/pypz-example
      recordCount: 30
      replicationFactor: 3
    spec:
      expectedParameters:
        message:
          currentValue: HelloWorld
          description: Specifies the message prefix for the record
          required: false
          type: str
        operatorImageName:
          currentValue: accessible-repository/pypz-example
          description: The image containing the operator's resources. It will be used
            mainly by the deployers.
          required: false
          type: str
        recordCount:
          currentValue: 30
          description: Specifies number of records to send
          required: true
          type: int
        replicationFactor:
          currentValue: 3
          description: Determines, how many replicas shall be created from the original.
          required: false
          type: int
      location: null
      name: pypz.example.writer:DemoWriterOperator
      nestedInstanceType: <class 'pypz.core.specs.plugin.Plugin'>
      nestedInstances:
      - dependsOn: []
        name: output_port
        parameters:
          channelConfig: {}
          portOpenTimeoutMs: 0
        spec:
          expectedParameters:
            channelConfig:
              currentValue: {}
              description: Configuration of the channel as dictionary
              required: false
              type: dict
            channelLocation:
              currentValue: KAFKA_BROKER_URL
              description: Location of the channel resource
              required: true
              type: str
            portOpenTimeoutMs:
              currentValue: 0
              description: Specifies, how long the port shall wait for incomingconnections
              required: false
              type: int
          location: null
          name: pypz.plugins.kafka_io.ports:KafkaChannelOutputPort
          nestedInstanceType: null
          nestedInstances: null
          types:
          - <class 'pypz.core.specs.plugin.OutputPortPlugin'>
          - <class 'pypz.core.specs.plugin.ResourceHandlerPlugin'>
          - <class 'pypz.core.specs.plugin.ExtendedPlugin'>
      - dependsOn: []
        name: logger
        parameters:
          logLevel: INFO
        spec:
          expectedParameters:
            logLevel:
              currentValue: INFO
              description: null
              required: false
              type: str
          location: null
          name: pypz.plugins.loggers.default:DefaultLoggerPlugin
          nestedInstanceType: null
          nestedInstances: null
          types:
          - <class 'pypz.core.specs.plugin.LoggerPlugin'>
      types:
      - <class 'pypz.core.specs.operator.Operator'>
  types:
  - <class 'pypz.core.specs.pipeline.Pipeline'>